                                         -- INTERMEDIATE LEVEL (Aggregation, CASE, HAVING) --

-- 10 Find total revenue generated by each category.

SELECT 
    category,
    SUM(discountedSellingPrice * quantity) AS Total_revenue
FROM
    zepto
GROUP BY category
ORDER BY Total_revenue ASC;

-- 11 Identify the top 5 best-selling products.

SELECT 
    *
FROM
    zepto
ORDER BY quantity DESC
LIMIT 5;


-- 12 Find categories where average discount is more than 10%.

SELECT Category,
       AVG(dicountPercent) AS avg_discount
FROM zepto
GROUP BY Category
HAVING AVG(dicountPercent) > 10;

-- 13 Classify products as:High Discount (>20%)Medium Discount (10–20%)Low Discount (<10%)

SELECT 
    name,
    dicountPercent,
    CASE 
        WHEN  dicountPercent > 20 THEN 'High Discount'
        WHEN  dicountPercent BETWEEN 10 AND 20 THEN 'Medium Discount'
        ELSE 'Low Discount'
    END AS discount_category
FROM zepto;

-- 14 Find products with high stock but low sales.(Hint: Available_Quantity > 20 AND Selling_Quantity < 5)

SELECT 
*
FROM zepto
WHERE availableQuantity > (
        SELECT AVG(availableQuantity) 
        FROM zepto
      )
AND quantity < (
        SELECT AVG(quantity) 
        FROM zepto
      );

-- 15 Calculate price per gram for each product.

SELECT 
    sku_id,
    name,
    discountedSellingPrice,
    weightInGms,
    ROUND( discountedSellingPrice * 1.0 / weightInGms, 2) AS price_per_gram
FROM zepto;